apiVersion: v1
kind: Service
metadata:
  name: chronos-os
  namespace: chronos
  labels:
    app.kubernetes.io/name: chronos
    app: chronos-os
spec:
  type: ClusterIP
  selector:
    app: chronos-os
  ports:
    - name: http
      port: 8420
      targetPort: http
      protocol: TCP
